Exit if gnupg version is 2.2.22 or 2.2.2
DataDog/yubikey pull request #60
Opened 2020-10-27 16:46 UTC by daisukixci

Gnupg has a bug in version 2.2.22 or 2.2.23 that makes gpg.sh fails
```bash
gpg/card> generate
Make off-card backup of encryption key? (Y/n) n
Please note that the factory settings of the PINs are
   PIN = '123456'     Admin PIN = '12345678'
You should change them using the command --change-pin
gpg: error checking the PIN: End of file
gpg/card> 58072933
Invalid command  (try "help")
```
See https://dev.gnupg.org/T5086 for more details. The issue has been fixed by https://dev.gnupg.org/T5052
and will be available in 2.2.24.

So I added an exit if gnupg version is 2.2.22 or 2.2.23 and made the upgrade/install with brew optional.
I added a check before running that all binaries needed are present.

2020-10-27 17:12 UTC, trishankatdatadog requested changes
Looks good, but please reintroduce all the changes we made for shellcheck, such as using quotes in echo, and read -rp, please...

2020-10-27 17:23 UTC, daisukixci commented
> Looks good, but please reintroduce all the changes we made for shellcheck, such as using quotes in echo, and read -rp, please...

done, sorry I f**** up something with a git checkout at some point

2020-10-27 17:26 UTC, trishankatdatadog commented on realname-and-email.sh
> -source env.sh
This will break `gpg.sh`. Either we bring back this line here, or add it there.

2020-10-27 17:30 UTC, daisukixci commented on realname-and-email.sh
> -source env.sh
I added it directly in gpg.sh line 50

2020-10-29 17:03 UTC, daisukixci commented on realname-and-email.sh
> -source env.sh
done

2020-10-30 14:44 UTC, trishankatdatadog approved these changes
Not entirely happy with adding friction for the common use case where the user may not care about updating dependencies, but I guess this is OK since this is all a rare operation, and it's good not to update destructively without asking for permission.

2020-10-30 15:25 UTC, merged