Enforce cryptographic algorithms
DataDog/yubikey pull request #64
Opened 2021-01-14 16:06 UTC by guedou

Here is a PR that specify which algorithms should be allowed or disabled.

2021-01-14 16:15 UTC, daisukixci commented on env.sh
> +
Do you mind if I sneak in you PR to make one backup function with a file list instead of duplicating the function ?

2021-01-14 16:18 UTC, trishankatdatadog requested changes

2021-01-14 16:18 UTC, trishankatdatadog commented on env.sh
> +export GIT=/usr/bin/git
Let's drop this for this PR. We can reconsider git in a different PR.

2021-01-14 16:18 UTC, trishankatdatadog commented on gpg.sh
> +cat << EOF > "$GPG_CONF"
Would you please explain the rationale for these choices, and references, if any?

2021-01-14 16:49 UTC, guedou commented on env.sh
> +export GIT=/usr/bin/git
Sorry, I should not have committed this line.

2021-01-14 16:50 UTC, guedou commented on gpg.sh
> +cat << EOF > "$GPG_CONF"
I added a note explaining why these algorithms were selected.

2021-01-14 16:50 UTC, guedou commented on env.sh
> +
Feel free to push commits on top of this PR.

2021-01-14 17:38 UTC, trishankatdatadog commented on gpg.sh
> +cat << EOF > "$GPG_CONF"
A good reference would still help. Would you happen to have any?

2021-01-15 10:02 UTC, daisukixci commented on gpg.sh
> +cat << EOF > "$GPG_CONF"
Added FIPS certification link

2021-01-15 10:03 UTC, daisukixci commented on env.sh
> +
Done, thanks for your work 🙇

2021-01-15 19:10 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
LGTM. Just one more last thing: could we link to an example `gpg.conf` that inspired these choices, or was it manually derived?

2021-01-18 14:55 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Can't find similar configuration but since there is only two directives in it, I think a man gpg.conf is enough in that case

2021-01-18 15:46 UTC, guedou commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
I made the gpg.conf file by looking at the man page to disable weaker cryptographic algorithms.

To be fair, I don't have strong arguments against ElGamal, Camellia & Twofish.

2021-01-19 12:28 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Since we do not generally use the applet to encrypt, should we just focus on things that affect signing (e.g., digest algos) for now, and leave out cipher/compression/pubkey algos?

2021-01-19 12:29 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
I use it to encrypt too, i'm happy to have it and i don't feel like it's a bad thing to enforce those

2021-01-19 13:12 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Yeah, might not be a bad idea to enforce these things, except that I'm not sure about algos like ElGamal (haven't heard of anyone using it, so might be a good argument for turning it off by default). I think I'd just like to see a bit of an argument for why not some of these things, and then I'm happy to approve.

2021-01-19 15:07 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Not being FIPS compliant is not enough ?

2021-01-19 16:30 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Good enough for me: I trust that you have checked. Thanks!

2021-01-19 16:37 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
BTW, certain keying options of 3DES are allowed in FIPS 140-2, so 🤷🏽‍♂️

2021-01-20 09:13 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Will be deprecated in 2023 https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-131Ar2.pdf for legacy apps and already deprecated for new apps

2021-01-20 09:15 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
Added the link in the script

2021-01-20 10:33 UTC, trishankatdatadog commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
I will let you approve and merge this PR when you think it's ready @daisukixci

2021-01-20 10:57 UTC, daisukixci commented on gpg.sh
> +# https://csrc.nist.rip/groups/STM/cmvp/documents/140-1/140crt/140crt1130.pdf
You have to approve since you requested change, don't you

2021-01-20 11:01 UTC, daisukixci approved these changes

2021-01-21 14:48 UTC, trishankatdatadog submitted a review, later dismissed

2021-01-21 14:48 UTC, trishankatdatadog commented
@guedou can you rebase and sign your commits? ;)

2021-01-26 13:42 UTC, guedou commented
@trishankatdatadog Sorry for the delay. Is it OK if I squash @daisukixci commits? I did not find a way to sign my past commits.

By the way, 1Password displays the PINs strength as 'terrible'.

2021-01-26 13:50 UTC, daisukixci commented
> @trishankatdatadog Sorry for the delay. Is it OK if I squash @daisukixci commits? I did not find a way to sign my past commits.

Yes be my guest. To sign your old commit, you have to rebase.

> By the way, 1Password displays the PINs strength as 'terrible'.
Yeah 1password doesn't know how to evaluate PIN security :$

2021-01-26 14:15 UTC, guedou commented
Done!

2021-01-26 14:16 UTC, daisukixci approved these changes

2021-01-26 14:17 UTC, merged