Add troubleshooting instructions for perpetual PIN entry case
DataDog/yubikey pull request #83
Opened 2021-05-24 22:06 UTC by xornivore

2021-05-25 00:41 UTC, trishankatdatadog requested changes

2021-05-25 00:41 UTC, trishankatdatadog commented on docs/troubleshooting.md
> +## Key not recognized blocking code signing on PIN Entry
Please link to this subsection from the ToC above.

2021-05-25 00:41 UTC, trishankatdatadog commented on gpg-gen-scdaemon-conf.sh
> +echo "${GREEN}Generating scdaemon.conf."
I think we can add the `${RESET}` at the end of the line, no?

2021-05-25 00:41 UTC, trishankatdatadog commented on gpg-gen-scdaemon-conf.sh
> +#!/usr/bin/env bash
Could we:
1. rename this script to `scdaemon.sh`?
2. call this script from `gpg.sh`?

2021-05-25 14:21 UTC, daisukixci commented on scdaemon.sh
> +source env.sh
```suggestion
[[ ${BASH_SOURCE[0]} != "$0" ]] || source env.sh
```

2021-05-26 02:41 UTC, trishankatdatadog requested changes

2021-05-26 02:41 UTC, trishankatdatadog commented on docs/troubleshooting.md
> +--[Card-not-recognized-with-perpetual-PIN-entry-prompt](#card-not-recognized-with-perpetual-pin-entry-prompt)
Maybe call it `Unsupported device` or whatever the precise error message is, easier to find.

2021-05-26 02:41 UTC, trishankatdatadog commented on docs/troubleshooting.md
> +Run [gpg-gen-scdaemon-conf.sh](../scdaemon.sh), then `killall gpg-agent`.
```suggestion
Run [./scdaemon.sh](../scdaemon.sh).
```

2021-05-26 02:41 UTC, trishankatdatadog commented on docs/troubleshooting.md
> +Run [gpg-gen-scdaemon-conf.sh](../scdaemon.sh), then `killall gpg-agent`.
No `killall gpg-agent`. I will suggest something to add at the end of the script later.

2021-05-26 02:41 UTC, trishankatdatadog commented on scdaemon.sh
> +fi
```suggestion
fi

$GPGCONF --kill all
```

2021-05-26 20:31 UTC, xornivore commented on docs/troubleshooting.md
> +--[Card-not-recognized-with-perpetual-PIN-entry-prompt](#card-not-recognized-with-perpetual-pin-entry-prompt)
There isn't an error message per se, it just doesn't see it.

2021-05-26 21:01 UTC, trishankatdatadog approved these changes
💯

2021-05-26 21:01 UTC, merged